blank_issues_enabled: true
contact_links:
  - name: ğŸ—£ Subproject discussions 
    url: https://github.com/camaraproject/Â§repo_nameÂ§/discussions
    about: Please ask and answer questions here.
  - name: ğŸ“– CAMARA API Design Guidelines
    url: https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md
    about: Please refer to the design guidelines.
